### ISSUE TITLE
Privacy state not showing the right value on settings pop up

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/campaign_mgmt#1]
@jeroenooms The privacy state of 3182015 campaign is private but the privacy state on the Settings pop up shows "off"
![capture](https://cloud.githubusercontent.com/assets/1034174/6720953/8de826b6-cd85-11e4-8992-bd7c41cb257c.PNG)

**Comment by hongsudt** [comment]
Can we changed the label on/off to something else?

For privacy state: it should be shared or private.. On/off is confusing.
Running is ok.

**Comment by ctrance** [comment]
@jeroenooms - Also if I turn off the privacy and save the changes, the state didn't reflect on the server.

**Comment by jeroen** [comment]
I have changed this to use the same layout and labels as the survey tool.

**Comment by jeroen** [comment]
@ctrance it should now also update the running state in the campaign table after you click 'save' (I assume that is what you meant). Could you test again when you have a chance?

**Comment by ctrance** [comment]
fixed
