### ISSUE TITLE
add "editable responses" switch to campaign edit modal

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/campaign_mgmt#5]
I think this applies to this tool as well:

as of https://github.com/ohmage/server/issues/888 we now support editable survey responses where applicable.  

Please add a toggle-able parameter which sets `editable: true/false` (default false) on the author tool.

Additionally! It would be best if this could be hidden if `app_name = mobilize` as this brings some serious downsides to participatory sensing studies.

**Comment by jeroen** [comment]
Added the 'editable' field to the table https://github.com/mobilizingcs/campaigns/commit/132d64efb8fe9cd54f70072dc91e2bb1fead60c4 and a switch to the modal https://github.com/mobilizingcs/campaigns/commit/d9766a2c1b49ce7d1c670ee8b453355033a6b873.

**Comment by stevenolen** [comment]
Any chance we could get this hidden if app name is mobilize? 

Looks good!

**Comment by jeroen** [comment]
Yes it already does that

**Comment by jeroen** [comment]
No wait that's for the author app

**Comment by stevenolen** [comment]
looks good now, thanks!
