### ISSUE TITLE
slow loading when user can access many campaigns

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/campaign_mgmt#6]
looking at this from the server side: https://github.com/ohmage/server/issues/880, it's definitely non-trivial.  It can be done, but perhaps we can start by not loading response counts if the user has access to over 100 campaigns.

If the user is in this situation, it would be great to make a `function/read` call when
- the user expands a particular campaign's row
- the user clicks response or viz tools to navigate away (in order to hinder them from visiting if there are no visible responses).

**Comment by jeroen** [comment]
The thing is though that you can no longer sort by responses if you lazy load them. That might cripple the tool a bit in an unexpected way.

**Comment by stevenolen** [comment]
@jeroenooms

**Comment by jeroen** [comment]
Now using the batch user counts: https://github.com/mobilizingcs/campaigns/commit/3dc6f63ec5816c85982b949bc5a970bd758dfd63

**Comment by jeroen** [comment]
We can speed this if there would be an output type of `/campaign/read` which returns counts without all the `xml` data.

**Comment by jeroen** [comment]
@steven does the [campaign manager](https://test.mobilizingcs.org/#campaigns/) now load a bit faster for you? It seems to load in about 2sec for me, but I have "only"  371 campaigns ...

**Comment by stevenolen** [comment]
it's definitely loading faster, yes!  I could add the responses summary to `campaign/read output_format:short`, but it feels a bit wrong to add a bunch of extra processing time to the short call...I think this will do just fine! Thanks!
